{% set name = "seamless-3dep" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seamless_3dep-{{ version }}.tar.gz
  sha256: 4044515c1b8deed9a87b6de51d46fc56f5879a248f9a0d2219a55d946902d6dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - aiofiles
    - aiohttp >=3.8.3
    - libgdal-core
    - rasterio

test:
  imports:
    - seamless_3dep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Streamlined Access to USGS 3DEP Topographic Data
  license: MIT
  license_file: LICENSE
  home: https://github.com/hyriver/seamless-3dep

extra:
  recipe-maintainers:
    - cheginit
