{% set name = "seamless-3dep" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seamless_3dep-{{ version }}.tar.gz
  sha256: 945dc916c66168d482ba3251404b46918bc992ca956d2e43b29f85de088aad01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - rasterio

test:
  imports:
    - seamless_3dep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Easy retrieval of smealess DEM from 3DEP across US.
  license: MIT
  license_file: LICENSE
  home: https://github.com/hyriver/seamless-3dep

extra:
  recipe-maintainers:
    - cheginit
